invenio_indexer/api.py, invenio_indexer/utils.py
* Promotes _record_to_index to public method. (closes #5)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> api: promote _record_to_index to public method

.travis.yml, CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
=> release: v1.0.0a1

setup.py, tests/conftest.py
* Removes obsolete configuration.
(see inveniosoftware/invenio-search@cc05a96062370565085bb)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: SEARCH_AUTOINDEX removal

CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
=> release: v1.0.0a2

invenio_indexer/api.py, tests/demo/json_resolver.py, tests/test_api.py
* Adds support for replacing JSONRefs prior to indexing.
NOTE: Tests are missing
=> api: jsonref replacement on indexing

invenio_indexer/api.py, tests/test_api.py, tests/test_utils.py
* Fixes issue with jsonref preprocessing of records resulting in
dictionaries which are not JSON serializable.
=> api: json serialization fix

invenio_indexer/api.py, tests/test_api.py
* Improves error handling during bulk indexing to prevent broken
JSONRefs and similar issues to stop bulk indexing.
=> api: error handling improvements

CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
=> release: v1.0.0a3

setup.py
--
needed for https://github.com/zenodo/zenodo/issues/544
=> installation: fix API app entrypoint

CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
=> release: v1.0.0a4

invenio_indexer/version.py
=> version: post-release bump

invenio_indexer/api.py, setup.py, tests/test_api.py
* Adds record created/updated timestamps to all indexed records.
=> api: created/updated indexing

CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
=> release: v1.0.0a5

AUTHORS.rst, CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
=> release: v1.0.0a6

.gitignore, MANIFEST.in, examples/app-recreate.sh, examples/app.py, examples/data/testrecords/testrecord-v1.0.0.json
* Example app addition. (addresses #31)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> examples: addition of simple application

invenio_indexer/__init__.py, invenio_indexer/api.py, invenio_indexer/ext.py, invenio_indexer/proxies.py, invenio_indexer/utils.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> global: configurable record_to_index function

INSTALL.rst, MANIFEST.in, README.rst, RELEASE-NOTES.rst, docs/requirements.txt
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> docs: move to readthedocs.io

CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
--
It should solve a failing tests in https://github.com/inveniosoftware/invenio-collections/pull/70
=> release: v1.0.0a8

setup.py, tests/test_utils.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> installation: celery version fix

.editorconfig, .gitignore, CONTRIBUTING.rst, MANIFEST.in, README.rst, docs/conf.py, setup.py, tests/test_examples_app.py
* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>
=> global: release checklist

tests/test_utils.py
We have to use `db.get_app()` because Flask-SQLAlchemy v2.2 changed the way it picks a sender for the model signals.
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
Co-authored-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> tests: model signal connection SQLAlchemy 2.2

docs/api.rst, docs/conf.py, invenio_indexer/__init__.py, invenio_indexer/api.py
* (closes #60).
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> docs: add missing api docs

invenio_indexer/api.py, invenio_indexer/utils.py, setup.py
* Use the connection pool for establishing connections with the backend.
(closes #65)
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>
=> global: connection pool usage

examples/app-fixtures.sh, examples/app.py, invenio_indexer/cli.py, setup.py, tests/test_cli.py
* Reindex command now won't index deleted records (records without PID)
(closes #55).
=> cli: reindex ignores deleted records

CHANGES.rst, RELEASE-NOTES.rst, invenio_indexer/version.py
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> release: v1.0.0a10

invenio_indexer/api.py, tests/test_api.py
* Add class wich uses bulk indexing by default (closes #73).
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> api: add BulkRecordIndexer utility class

invenio_indexer/cli.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> cli: addition of queue option in ``run``

CHANGES.rst, invenio_indexer/version.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> release: v1.0.0b2

invenio_indexer/ext.py
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
=> ext: add TIND copyright information

CHANGES.rst
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> global: updated CHANGES.rst file

invenio_indexer/__init__.py, setup.py
Fix isort build error.
Closes #102
=> global: sort imports

CHANGES.rst, invenio_indexer/version.py
closes https://github.com/inveniosoftware/invenio-indexer/pull/97
=> release: v1.0.2

docs/conf.py, pytest.ini, run-tests.sh, setup.py
Addresses inveniosoftware/opensource#65
=> isort-fixing

.github/workflows/tests.yml, docs/conf.py, invenio_indexer/cli.py, run-tests.sh, setup.py, tests/conftest.py, tests/test_api.py, tests/test_cli.py, tests/test_invenio_indexer.py, tests/test_tasks.py, tests/test_utils.py
Needs to be backward compatible with Click 7
=> global: click v8.1 support

invenio_indexer/config.py, invenio_indexer/registry.py, tests/test_registry.py
- closes https://github.com/inveniosoftware/invenio-communities/issues/584
Video demo and images in the invenio-app-rdm PR
=> support all() and add max consumers config

CHANGES.rst, invenio_indexer/api.py, invenio_indexer/version.py, tests/conftest.py, tests/test_api.py
- closes https://github.com/inveniosoftware/invenio-communities/issues/620
=> api: add index refresh

invenio_indexer/api.py, invenio_indexer/config.py
=> api: add publish kwargs config

CHANGES.rst, invenio_indexer/__init__.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release: v2.1.2

.github/workflows/tests.yml, invenio_indexer/cli.py, tests/test_cli.py
=> cli: add queue selection options

.github/workflows/tests.yml, invenio_indexer/cli.py
:heart: Thank you for your contribution!
New parameter to the `index run` to specify the chunk_size
=> cli: run command accepts a new parameter 'chunk_size'

invenio_indexer/api.py
Required for https://github.com/inveniosoftware/invenio-audit-logs/pull/1
Closes https://github.com/CERNDocumentServer/cds-rdm/issues/361
=> api: Add indexing to datastream
